library(devtools)
library(slam)
library(skmeans)
library(rngtools)
library(mclust)
library(raster)
library(schoolmath)
library(NbClust)
library(ggplot2)
library(factoextra)
library(NMF)
library(FactoMineR)
library(skmeans)
data = read.csv("matrice-binary-25.csv")
dim(data)
d = as.matrix(as.data.frame(lapply(data, as.numeric)))
x50_sk_binary_wss = fviz_nbclust(t(d),skmeans, k.max=1641, method = "wss")
png('x50_sk_binary_wss.png',width=3840,height=2160)
plot(x50_sk_binary_wss)
dev.off()
x50_sk_binary_silhouette = fviz_nbclust(t(d),skmeans, k.max=1641, method = "silhouette")
png('x25_sk_binary_silhouette.png',width=3840,height=2160)
plot(x50_sk_binary_silhouette)
dev.off()
