library(devtools)
library(slam)
library(skmeans)
library(rngtools)
library(mclust)
library(raster)
library(schoolmath)
library(NbClust)
library(ggplot2)
library(factoextra)
library(NMF)
library(FactoMineR)
library(skmeans)
data = read.csv("matrice-binary-50.csv")
dim(data)
d = as.matrix(as.data.frame(lapply(data, as.numeric)))
x50_k_binary_silhouette = fviz_nbclust(t(d), diss=dist(t(d),method="manhattan"),kmeans, k.max=1641, method = c("silhouette"))
png('x50_k_binary_silhouette.png',width=3840,height=2160)
plot(x50_k_binary_silhouette)
dev.off()
x50_k_binary_wss = fviz_nbclust(t(d), diss=dist(t(d),method="manhattan"),kmeans, k.max=1641, method = c("wss"))
png('x50_k_binary_wss.png',width=3840,height=2160)
plot(x50_k_binary_wss)
dev.off()
