library(devtools)
library(slam)
library(skmeans)
library(rngtools)
library(mclust)
library(raster)
library(schoolmath)
library(NbClust)
library(ggplot2)
library(factoextra)
library(NMF)
library(FactoMineR)
library(skmeans)
data = read.csv("matrice-greyscale-25.csv")
dim(data)
d = as.matrix(as.data.frame(lapply(data, as.numeric)))
x25_sk_greyscale_wss = fviz_nbclust(t(d),skmeans, k.max=552, method = "wss")
png('x25_sk_greyscale_wss.png',width=3840,height=2160)
plot(x25_sk_greyscale_wss)
dev.off()
x25_sk_greyscale_silhouette = fviz_nbclust(t(d),skmeans, k.max=552, method = "silhouette")
png('x25_sk_greyscale_silhouette.png',width=3840,height=2160)
plot(x25_sk_greyscale_silhouette)
dev.off()
