library(devtools)
library(slam)
library(skmeans)
library(rngtools)
library(mclust)
library(raster)
library(schoolmath)
library(NbClust)
library(ggplot2)
library(factoextra)
library(NMF)
library(FactoMineR)
library(skmeans)
data = read.csv("matrice-greyscale-50.csv")
dim(data)
d = as.matrix(as.data.frame(lapply(data, as.numeric)))
x50_sk_greyscale_silhouette = fviz_nbclust(t(d), diss=dist(t(d),method="manhattan"),skmeans, k.max=1641, method = c("silhouette"))
png('x50_sk_greyscale_silhouette_greyscale.png',width=3840,height=2160)
plot(x50_sk_greyscale_silhouette)
dev.off()
x50_sk_greyscale_wss = fviz_nbclust(t(d), diss=dist(t(d),method="manhattan"),skmeans, k.max=1641, method = c("wss"))
png('x50_sk_greyscale_wss_binary_greyscale.png',width=3840,height=2160)
plot(x50_sk_greyscale_wss)
dev.off()
