library(devtools)
library(slam)
library(skmeans)
library(rngtools)
library(mclust)
library(raster)
library(schoolmath)
library(NbClust)
library(ggplot2)
library(factoextra)
library(NMF)
library(FactoMineR)
library(skmeans)
data = read.csv("matrice-binary-25.csv")
dim(data)
d = as.matrix(as.data.frame(lapply(data, as.numeric)))
bouh_25_binary = Mclust(t(d),G=1:552)
png('mclust_25_binary.png',width=3840,height=2160)
plot(bouh_25_binary)
dev.off()
